### ISSUE TITLE
rpn option

### ISSUE THREAD

**Issue by broomdodger** [eGust/calc.js#1]
Any chance you can provide an option for `rpn` input?

**Comment by eGust** [comment]
You mean Reverse Polish Notation? I can introduce a new syntax like this:

> #RPN{N1 N2 O1 N3 O2...}

Then I'll add a button/menu on the UI for inputting `#RPN{}` and give it a shortcut like `Ctrl+R` or something. 
Is that OK?

**Comment by broomdodger** [comment]
Yes, RPN == Reverse Polish Notation
RPN is also known as `postfix` vs infix notation

Can the `#RPN{}` be hidden?
ie the calculation without the surrounding `#RPN{}`

In the lower left is a `C` that could change to `R` when in RPN mode

BTW... Has the `R` button changed to the `C` button?

In the `About` it is written:

```
Basic Operations:
Input expression, press ENTER or click the R button.
```

**Comment by eGust** [comment]
All right. I'll add an option to switch the default mode. This feature shall be done in the next week.
And yes... I forgot that change -___-
